### ISSUE TITLE
Roadmap - Milestones

### ISSUE THREAD

**Issue by irenkai** [rotvulpix/transbank-laravel5#3]
Estimado, me gustaria colaborarle en el proyecto pero estoy medio perdido del estado en que esta. Hay algun roadmap de donde puedo entrar a picar para ayudar a que esto llegue a puerto (nos ahorre a todos las mil y una rabias clasicas del KCC).

**Comment by rotvulpix** [comment]
El proyecto, tal como en la versión laravel está funcionando aunque le falta "paquetizarlo"... tengo intención de retomarlo este fds para finalizarlo definitivamente :)
